//#include <Adafruit_NeoPixel.h>
#include <Adafruit_NeoPXL8.h> // > Scorpio!

#define SoundSensorPin A1  //this pin read the analog voltage from the sound level meter
#define VREF  5.0  //voltage on AREF pin,default:operating voltage

#define NUMPIXELS 12      // number of neopixels
#define COLOR_ORDER NEO_GRB // NeoPixel color format (see Adafruit_NeoPixel)

int8_t pins[8] = { NUMPIXELS, -1, -1, -1, -1, -1, -1, -1 }; // only one neopixel on pin 0
Adafruit_NeoPXL8 pixels(NUMPIXELS, pins, COLOR_ORDER);


void setup() {
  Serial.begin(9600);
  pixels.begin();
  pixels.fill(pixels.Color(0, 0, 0));
  pixels.show();
  delay(1000);
}

void loop() {
  pixels.clear();

  // read the value from the sensor:
  float voltageValue,dbValue;
  voltageValue = analogRead(SoundSensorPin) / 1024.0 * VREF;
  dbValue = voltageValue * 50.0;  //convert voltage to decibel value
  Serial.print(dbValue,1);
  Serial.println(" dBA");

  int dBColor = map(dbValue, 30, 130, 90, 0); // red to green in color wheel
  pixels.fill(Wheel(dBColor));  // insert HSB value generated by function Wheel()

  // pixels.setPixelColor(0, pixels.Color(0, 150, 0));

  pixels.show(); 

  delay(50);
}




// function wheel: input 0-255 in order to get RGB from color wheel
uint32_t Wheel(byte WheelPos) {
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return pixels.Color(255 - WheelPos * 3, 0, WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return pixels.Color(0, WheelPos * 3, 255 - WheelPos * 3);
  }
  WheelPos -= 170;
  return pixels.Color(WheelPos * 3, 255 - WheelPos * 3, 0);
}