#include <Adafruit_NeoPXL8.h>

#define NUMPIXELS 24      // number of neopixels
#define COLOR_ORDER NEO_GRB // NeoPixel color format (see Adafruit_NeoPixel)

//int8_t pins[8] = { 16, 17, 18, 19, 20, 21, 22, 23 }; // all 8 pins
int8_t pins[8] = { 16, -1, -1, -1, -1, -1, -1, -1 }; // only one neopixel on pin 0
Adafruit_NeoPXL8 pixels(NUMPIXELS, pins, COLOR_ORDER);

void setup() {
  pixels.begin();        // initialize neopixels with neodriver address
  pixels.setBrightness(20);  // set lower brightness
  pixels.show();
}

int w = 0;

void loop() {
  pixels.clear();

  pixels.fill(Wheel(w));  // insert HSB value generated by function Wheel()

  if (w < 255)
    w += 1;
  else
    w = 0;

  pixels.show();            // without show there will be no update

  //delay(200);               // set speed / slowdown

}


// function wheel: input 0-255 in order to get RGB from color wheel
uint32_t Wheel(byte WheelPos) {
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return pixels.Color(255 - WheelPos * 3, 0, WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return pixels.Color(0, WheelPos * 3, 255 - WheelPos * 3);
  }
  WheelPos -= 170;
  return pixels.Color(WheelPos * 3, 255 - WheelPos * 3, 0);
}